import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import { Provider } from "@/shared/utils/Provider";
import { StoreProvider } from "@/shared/redux/storeProvider";

const OutFit = localFont({
  src: "../fonts/Outfit-Regular.ttf",
  variable: "--font-outfit",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${OutFit.variable} font-sans antialiased bg-[#f7f8fc]`}>
        <StoreProvider>
          <Provider>{children}</Provider>
        </StoreProvider>
      </body>
    </html>
  );
}
